WIP - Docker compose

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -138,6 +138,106 @@ services:
       sh -c "exec sentry run web"
 
   # ---- Apache AirFlow ----
+  airflow-init:
+    image: apache/airflow:latest
+    container_name: airflow-init
+    env_file:
+      - .env.dev
+    environment:
+      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
+      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:password@pgvector/airflow
+      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:password@pgvector/airflow
+      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/1
+      AIRFLOW__CORE__FERNET_KEY: ''
+      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
+      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
+      _AIRFLOW_DB_MIGRATE: 'true'
+      _AIRFLOW_WWW_USER_CREATE: 'true'
+      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+      AIRFLOW_CONN_PGVECTOR_CONN: postgres://postgres:password@pgvector/vectordb
+      AIRFLOW_CONN_QDRANT_REST: http://qdrant:6333
+      AIRFLOW_CONN_REDIS: redis://:${REDIS_PASSWORD}@redis:6379/0
+      AIRFLOW_CONN_MINIO: s3://minioadmin:minioadmin@minio:9000
+      AIRFLOW_CONN_NEO4J_DEFAULT: neo4j://neo4j:password@neo4j:7687/neo4j
+      _PIP_ADDITIONAL_REQUIREMENTS:
+    volumes:
+      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
+      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
+      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
+      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
+      - ${AIRFLOW_PROJ_DIR:-.}:/sources
+    entrypoint: /bin/bash
+    command: |
+      -c "
+        function ver() {
+          printf \"%04d%04d%04d%04d\" $${1//./ }
+        }
+        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.2.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        # if (( airflow_version_comparable < min_airflow_version_comparable )); then
+        #   echo
+        #   echo -e \"\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m\"
+        #   echo \"The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!\"
+        #   echo
+        #   exit 1
+        # fi
+        if [[ -z \"\$${AIRFLOW_UID}\" ]]; then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m\"
+          echo \"If you are on Linux, you SHOULD follow the instructions below to set \"
+          echo \"AIRFLOW_UID environment variable, otherwise files will be owned by root.\"
+          echo \"For other operating systems you can get rid of the warning with manually created .env file:\"
+          echo \"    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user\"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources=\"false\"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m\"
+          echo \"At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))\"
+          echo
+          warning_resources=\"true\"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m\"
+          echo \"At least 2 CPUs recommended. You have $${cpus_available}\"
+          echo
+          warning_resources=\"true\"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m\"
+          echo \"At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))\"
+          echo
+          warning_resources=\"true\"
+        fi
+        if [[ $${warning_resources} == \"true\" ]]; then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m\"
+          echo \"Please follow the instructions to increase amount of resources available:\"
+          echo \"   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin\"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R \"$${AIRFLOW_UID}:0\" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow db migrate && airflow users create --username admin --firstname Peter --lastname Parker --role Admin --email spiderman@superhero.org --password admin
+      "
+    user: root
+    depends_on:
+      pgvector:
+        condition: service_started
+      redis:
+        condition: service_started
+
   airflow-webserver:
     image: apache/airflow:latest
     container_name: airflow-webserver
@@ -307,106 +407,6 @@ services:
         condition: service_started
       airflow-init:
         condition: service_completed_successfully
-
-  airflow-init:
-    image: apache/airflow:latest
-    container_name: airflow-init
-    env_file:
-      - .env.dev
-    environment:
-      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
-      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:password@pgvector/airflow
-      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:password@pgvector/airflow
-      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/1
-      AIRFLOW__CORE__FERNET_KEY: ''
-      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
-      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
-      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
-      _AIRFLOW_DB_MIGRATE: 'true'
-      _AIRFLOW_WWW_USER_CREATE: 'true'
-      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
-      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
-      AIRFLOW_CONN_PGVECTOR_CONN: postgres://postgres:password@pgvector/vectordb
-      AIRFLOW_CONN_QDRANT_REST: http://qdrant:6333
-      AIRFLOW_CONN_REDIS: redis://:${REDIS_PASSWORD}@redis:6379/0
-      AIRFLOW_CONN_MINIO: s3://minioadmin:minioadmin@minio:9000
-      AIRFLOW_CONN_NEO4J_DEFAULT: neo4j://neo4j:password@neo4j:7687/neo4j
-      _PIP_ADDITIONAL_REQUIREMENTS:
-    volumes:
-      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
-      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
-      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
-      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
-      - ${AIRFLOW_PROJ_DIR:-.}:/sources
-    entrypoint: /bin/bash
-    command: |
-      -c "
-        function ver() {
-          printf \"%04d%04d%04d%04d\" $${1//./ }
-        }
-        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO airflow version)
-        airflow_version_comparable=$$(ver $${airflow_version})
-        min_airflow_version=2.2.0
-        min_airflow_version_comparable=$$(ver $${min_airflow_version})
-        # if (( airflow_version_comparable < min_airflow_version_comparable )); then
-        #   echo
-        #   echo -e \"\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m\"
-        #   echo \"The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!\"
-        #   echo
-        #   exit 1
-        # fi
-        if [[ -z \"\$${AIRFLOW_UID}\" ]]; then
-          echo
-          echo -e \"\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m\"
-          echo \"If you are on Linux, you SHOULD follow the instructions below to set \"
-          echo \"AIRFLOW_UID environment variable, otherwise files will be owned by root.\"
-          echo \"For other operating systems you can get rid of the warning with manually created .env file:\"
-          echo \"    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user\"
-          echo
-        fi
-        one_meg=1048576
-        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
-        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
-        disk_available=$$(df / | tail -1 | awk '{print $$4}')
-        warning_resources=\"false\"
-        if (( mem_available < 4000 )) ; then
-          echo
-          echo -e \"\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m\"
-          echo \"At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))\"
-          echo
-          warning_resources=\"true\"
-        fi
-        if (( cpus_available < 2 )); then
-          echo
-          echo -e \"\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m\"
-          echo \"At least 2 CPUs recommended. You have $${cpus_available}\"
-          echo
-          warning_resources=\"true\"
-        fi
-        if (( disk_available < one_meg * 10 )); then
-          echo
-          echo -e \"\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m\"
-          echo \"At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))\"
-          echo
-          warning_resources=\"true\"
-        fi
-        if [[ $${warning_resources} == \"true\" ]]; then
-          echo
-          echo -e \"\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m\"
-          echo \"Please follow the instructions to increase amount of resources available:\"
-          echo \"   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin\"
-          echo
-        fi
-        mkdir -p /sources/logs /sources/dags /sources/plugins
-        chown -R \"$${AIRFLOW_UID}:0\" /sources/{logs,dags,plugins}
-        exec /entrypoint airflow db migrate && airflow users create --username admin --firstname Peter --lastname Parker --role Admin --email spiderman@superhero.org --password admin
-      "
-    user: root
-    depends_on:
-      pgvector:
-        condition: service_started
-      redis:
-        condition: service_started
 
   airflow-cli:
     image: apache/airflow:latest
